spring:
  datasource:
      url: jdbc:mysql://localhost:3306/bs?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
  port: 8082

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  params: count = countSql

